# Generated by Django 6.0.6 on 2026-06-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_recipe_prep_time_recipe_servings_recipe_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tags/categorias da receita (ex.: vegano, rápido).'),
        ),
    ]
